# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb4e6dd7114ef25d1bfe77258f7d5e897136429b2ec9b44ebcca6fe6b6ad31dba1c23dee086adad78292eb2fc56c32287fdaa42a1a29e2251baaa1da392c673a

test:
  secret_key_base: 4735dbc93251f1e7068d7776d525ddf9dc4e94ad52627d4633dde9e8e41b6756038ee8d529da1e4fdc44f4408e86104e7f86713a84d1fb777872ba71e9a09a85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
